main:
  - identifier: blog
    name: Blog
    weight: 4
    params:
      icon:
        vendor: fas
        name: blog

  - identifier: projects
    name: Projects
    weight: 10
    url: /project
    params:
      icon:
        vendor: fas
        name: list-check

  - name: Off Beat
    parent: projects
    url: /project/off-beat
    weight: 11
    params:
      icon:
        vendor: fas
        name: sailboat
      description: A slow boat.

  - name: Bilge Monitor
    parent: projects
    url: /project/bilge-monitor
    weight: 12
    params:
      icon:
        vendor: fas
        name: arrow-up-from-water-pump
      description: SignalK motor runtime monitor.

  - name: BCL
    parent: projects
    url: /project/bcl
    weight: 13
    params:
      icon:
        vendor: fas
        name: terminal
      description: Bob's command language interpreter.
